apiVersion: batch/v1
kind: CronJob
metadata:
  name: projectlive-nf
spec:
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: projectlive-nf
            image: andrewelamb/projectlive_nf_files:1.1.2
            imagePullPolicy: Always
            env:
              - name: SYNAPSE_AUTH_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: tyu-syn-pat
                    key: synapse_auth_token
          restartPolicy: OnFailure
