apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: database-data
  name: database-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
