apiVersion: v1
kind: Service
metadata:
  namespace: nlp
  labels:
    name: db
  name: db
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    name: db
status:
  loadBalancer: {}
