name: Apply updates
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - name: Assume AWS role
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.CI_SERVICE_USER_ACCESS_KEY }}
      #     aws-secret-access-key: ${{ secrets.CI_SERVICE_USER_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
      #     # role-to-assume: arn:aws:iam::841415736403:role/nlp-sandbox-ci-service-account-ServiceRole-1KF7Q6FCOOQRE
      #     role-duration-seconds: 1200
      # - uses: actions-hub/kubectl@v1.21.2
      #   env:
      #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      #   with:
      #     args: apply -f cronjobs
      - uses: Eyevinn/action-eks-kubectl@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_SERVICE_USER_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_SERVICE_USER_SECRET_ACCESS_KEY }}
          REGION: us-east-1
          CLUSTER: ibc
        with:
          args: apply -f cronjobs
